### ISSUE TITLE
Other projects do not work

### ISSUE THREAD

**Issue by qbicStefanC** [qbicsoftware/geo-uploader-cli#11]
Tool does not work for all projects: QMSUI, QMHBS do not work. 
Please fix and test for these projects again. If it still fails the tool should give feedback why (see also Issue Excel output).

**Comment by lucast122** [comment]
Can you give me access to these projects? It'll be much easier for me to debug it then. Working to fix the issues right now

**Comment by qbicStefanC** [comment]
You have access now

**Comment by lucast122** [comment]
I will work on this next Monday

**Comment by lucast122** [comment]
the first one works fine
still working on a minor issue for the 2nd project

**Comment by lucast122** [comment]
fixed with #38
