### ISSUE TITLE
Clean-up repo

### ISSUE THREAD

**Issue by qbicStefanC** [qbicsoftware/geo-uploader-cli#13]
There are a bunch of files that should be deleted from the repo:

-remove immediately all qbic project related tables and infos such as outputQGVIN.xlsx, QJWAB_identifiers,geo-uploader-cliQGVIN.xlsx,geo-uploader-cliQJWAB.xlsx,geo_template.xlsx...

-also remove the files .attach_pid17092, etc from the repo

**Comment by lucast122** [comment]
Removed the requested files as well as some other files from repo. Feel free to close the issue if you think it's fine now

**Comment by qbicStefanC** [comment]
Loos good now.Thx.
