### ISSUE TITLE
add -c command to example usage in readme

### ISSUE THREAD

**Issue by qbicStefanC** [qbicsoftware/geo-uploader-cli#15]
please add -c command to example usage in readme and make clear that when someone is not giving a config file, the example file will be used. 
Also make sure to add in the readme that the config file needs to be created.

We propose that in the next release there should be a download of the jar file and a small zip containing the config.yaml plus the template.xlsx file

**Comment by lucast122** [comment]
-c parameter is not optional anymore since you need to provide the appserver adress with the config to connect to openBIS (shouldnt put this on github, because of security issues)
I will put an example config.yaml in the next release
