### ISSUE TITLE
Remove binaries from code repository

### ISSUE THREAD

**Issue by chahuistle** [qbicsoftware/geo-uploader-cli#16]
We use Maven for dependency management, so there is no need to maintain the `classes` directory. 

This repository is 208 MB.

Maybe there is a good reason why this folder exists, but I cannot think of one.

**Comment by lucast122** [comment]
You are absolutely right, should have added this to .gitignore
I will delete these files

**Comment by lucast122** [comment]
I'm curious as I'm inexperienced with maven ... Does Maven automatically download the dependencies when the program is run or how does this work if the user does not have all dependencies installed?

**Comment by chahuistle** [comment]
>  should have added this to .gitignore

This will not solve the problem. This will only make it work on your computer. Any project generated with our cookiecutter templates already contains a preconfigured `.gitignore` file that works for most cases.

>  Does Maven automatically download the dependencies when the program is run or how does this work if the user does not have all dependencies installed?

Yes, that's the idea behind dependency management systems. These are some of [Maven's features](https://maven.apache.org/maven-features.html):
 
  * Superior dependency management including automatic updating, dependency closures (also known as transitive dependencies)
  * Dependency management: Maven encourages the use of a central repository of JARs and other dependencies. Maven comes with a mechanism that your project's clients can use to download any JARs required for building your project from a central JAR repository much like Perl's CPAN. This allows users of Maven to reuse JARs across projects and encourages communication between projects to ensure that backward compatibility issues are dealt with.

The [QBiC's developer guide](https://github.com/qbicsoftware/cookiecutter-templates-cli/blob/development/README_DEVELOPMENT.md#2-maven) points to Maven reading material.

**Comment by lucast122** [comment]
Thank you I'll do some reading
