### ISSUE TITLE
leaving off pw from the config.yaml file does not work

### ISSUE THREAD

**Issue by qbicStefanC** [qbicsoftware/geo-uploader-cli#28]
Pro:Geo-uploader StefanC$ java -jar geo-uploader-cli-1.2-jar-with-dependencies.jar -p QXXXX -o test -c config.yaml 
11:34:45.557 [main] DEBUG life.qbic.cli.main.MainEntryPoint - Starting Main tool
11:34:45.715 [main] WARN  life.qbic.cli.ToolExecutor - Missing tool descriptor file. Make sure the file tool.properties is located in the classpath
11:34:45.719 [main] WARN  life.qbic.cli.ToolExecutor - Missing value in tool.properties file for property 'tool.version', using default value '1.0.0-SNAPSHOT'
11:34:45.720 [main] WARN  life.qbic.cli.ToolExecutor - Missing value in tool.properties file for property 'tool.repo.url', using default value 'http://github.com/qbicsoftware'
11:34:45.720 [main] WARN  life.qbic.cli.ToolExecutor - Missing value in tool.properties file for property 'tool.name', using default value 'QBiC toolset'
11:34:45.723 [main] DEBUG life.qbic.cli.ToolExecutor - Starting execution
11:34:45.724 [main] INFO  life.qbic.cli.main.MainTool - Parse commands
Password: 
11:34:53.765 [main] DEBUG life.qbic.core.authentication.PostmanSessionManager - ch.systemsx.cisd.common.exceptions.UserFailureException: No 'password' specified.
11:34:53.765 [main] ERROR life.qbic.core.authentication.PostmanSessionManager - Connection to openBIS failed.
Could not connect to openBis. Check your config file
11:34:53.766 [Thread-1] DEBUG life.qbic.cli.ToolExecutor - Shutting down

**Comment by lucast122** [comment]
fixed with #30
