### ISSUE TITLE
Geo-Uploader Gives "null" back as result.

### ISSUE THREAD

**Issue by subwaystation** [qbicsoftware/geo-uploader-cli#9]
Hi Timo.
could you please take a look at this:

`heumos@wave ~/Downloads> java -cp geo-uploader-cli.jar life.qbic.cli.main.MainEntryPoint -u afaaj01 -p QMSUI -o geo_output/ -c config.yaml
Parse commands
openBis connection established
Password: 
Logged in successfully to openBis
Normal constructor
Found project QMSUI for user afaaj01
null
Check the application log in logs/app.log for more details.
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.`

`heumos@wave ~/Downloads> java -cp geo-uploader-cli.jar life.qbic.cli.main.MainEntryPoint -u afaaj01 -p QMHBS -o geo_output/ -c config.yaml
Parse commands
openBis connection established
Password: 
Logged in successfully to openBis
Normal constructor
Found project QMHBS for user afaaj01
null
Check the application log in logs/app.log for more details.
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
`
Best, Simon

**Comment by lucast122** [comment]
Gonna fix this next week

**Comment by lucast122** [comment]
new release works with both projects
